using CommunityToolkit.Maui.Views;
using Plugin.Maui.Calendar.Enums;
using SampleApp.Views;
namespace SampleApp.ViewModels;

public partial class CalendarPickerPopupViewModel : BasePageViewModel
{
    // Add property for parent popup
    //[ObservableProperty]
    //CommunityToolkit.Maui.Views.Popup parentPopup; // Fully qualify the type to resolve ambiguity

    // Add event for popup closure
    public event EventHandler<object> PopupClosureRequested;

    public CalendarPickerPopupViewModel() : base()
    {
        SelectedDate = DateTime.Today.Date;
    }

    public event Action<CalendarPickerResult> Closed;

    [ObservableProperty]
    DateTime shownDate = DateTime.Today;

    [ObservableProperty]
    WeekLayout calendarLayout = WeekLayout.Month;

    [ObservableProperty]
    DateTime? selectedDate;

    [ObservableProperty]
    DateTime minimumDate = new(1900, 1, 1);

    [ObservableProperty]
    DateTime maximumDate = DateTime.Today.AddDays(3);

	Popup parentPopup;

	// Regular property - not generated by ObservableProperty attribute
	public Popup ParentPopup
	{
		get => parentPopup;
		set => parentPopup = value;
	}

	[RelayCommand]
    void Clear()
    {
        SelectedDate = null;
    }

    [RelayCommand]
    async Task Success()
    {
        // Create the result
        var result = new CalendarPickerResult() { IsSuccess = SelectedDate.HasValue, SelectedDate = SelectedDate };

        // Invoke any event handlers
        Closed?.Invoke(result);

        // Close the popup and return true to indicate success
        await ClosePopupAsync(true);
    }

    [RelayCommand]
    async Task Cancel()
    {
        // Create the result
        var result = new CalendarPickerResult() { IsSuccess = false };

        // Invoke any event handlers
        Closed?.Invoke(result);

        // Close the popup and return false to indicate cancellation
        await ClosePopupAsync(false);
    }

    // Helper method to close the popup
    public async Task ClosePopupAsync(object result)
    {
        // Option 1: If your ViewModel has a property for the parent popup
        if (ParentPopup != null)
        {
            await ParentPopup.CloseAsync(result);
            return;
        }

        // Option 2: Using an event to request closure
        PopupClosureRequested?.Invoke(this, result);
    }
}
